apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xi8xveyz0-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c28cf31e31.b5uv.p3.openshiftapps.com/rhtap/rhtap-qe:437b42d9f145deb904e7fbd85c9f00f5d61d3794@sha256:04b4b152fda086d572907cd1d8fe7057d48fc9300052e00cbbe1fc3b435ab8e8
          name: container-image
